# Generated by Django 4.1 on 2022-12-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logicnodeinstantiated',
            name='instance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер экземпляра'),
        ),
    ]
