# Generated by Django 4.1 on 2022-12-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_types', '0002_alter_logicnodeinstantiated_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logicnodeinstantiated',
            name='short_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Краткое имя функции'),
        ),
    ]
