# Generated by Django 4.1 on 2022-12-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_types', '0003_alter_logicnodeinstantiated_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicnodeinstantiated',
            name='full_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Полное имя функции'),
        ),
    ]
