# Generated by Django 4.1 on 2022-12-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_types', '0004_logicnodeinstantiated_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logicnodeinstantiated',
            name='full_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Полное имя функции'),
        ),
    ]
