# Generated by Django 4.1 on 2022-12-11 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_types', '0005_alter_logicnodeinstantiated_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='Обозначение входа (напр.: С1, А4)')),
                ('sw_type', models.CharField(choices=[('SW.2', 'SW.2'), ('SW.2', 'SW.2'), ('-', '-')], default='-', max_length=4, verbose_name='Тип переключателя')),
                ('sw_name', models.CharField(blank=True, max_length=32, verbose_name='Обозначение переключателя')),
                ('description', models.CharField(max_length=128, verbose_name='Описание входа (напр.: АСУ / Режим работы)')),
            ],
            options={
                'verbose_name': 'Вход',
                'verbose_name_plural': 'Входы',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw_type', models.CharField(choices=[('SW.2', 'SW.2'), ('SW.3', 'SW.3')], default='SW.2', max_length=4, verbose_name='Тип')),
                ('short_name', models.CharField(max_length=32, verbose_name='Краткое обозначение')),
                ('description', models.TextField(blank=True, max_length=1024, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Переключатель',
                'verbose_name_plural': 'Переключатели',
                'ordering': ['sw_type'],
            },
        ),
        migrations.AlterField(
            model_name='logicnodeinstantiated',
            name='full_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='logicnodeinstantiated',
            name='short_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Краткое имя'),
        ),
        migrations.CreateModel(
            name='SwitchesAndLNs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ln', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_types.logicnodeinstantiated', verbose_name='Экземпляр лог. узла')),
                ('switch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_types.switch', verbose_name='Переключатель')),
            ],
            options={
                'verbose_name': 'Переключатель в составе ФЮ',
                'verbose_name_plural': 'Переключатели в составе ФЮ',
                'ordering': ['switch'],
            },
        ),
        migrations.CreateModel(
            name='InputsAndLNs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_types.input', verbose_name='Переключатель')),
                ('ln', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_types.logicnodeinstantiated', verbose_name='Экземпляр лог. узла')),
            ],
            options={
                'verbose_name': 'Вход в составе ФЮ',
                'verbose_name_plural': 'Входы составе ФЮ',
                'ordering': ['input'],
            },
        ),
    ]
