# Generated by Django 3.2.16 on 2022-12-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_types', '0006_input_switch_alter_logicnodeinstantiated_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputsandlns',
            options={'ordering': ['input'], 'verbose_name': 'Вход в составе ФБ', 'verbose_name_plural': 'Входы составе ФБ'},
        ),
        migrations.AlterModelOptions(
            name='switchesandlns',
            options={'ordering': ['switch'], 'verbose_name': 'Переключатель в составе ФБ', 'verbose_name_plural': 'Переключатели в составе ФБ'},
        ),
        migrations.AlterField(
            model_name='logicnodestypes',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Имя типа ЛУ'),
        ),
    ]
