# Generated by Django 3.2.16 on 2022-12-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_types', '0007_auto_20221212_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdcs',
            name='name',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='ОКД'),
        ),
        migrations.AlterField(
            model_name='clueattrs',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='datasets',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Датасет'),
        ),
        migrations.AlterField(
            model_name='signals',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Сигналы'),
        ),
        migrations.AlterField(
            model_name='statuses',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Статусы сигнала'),
        ),
    ]
