# Generated by Django 3.2.16 on 2022-12-12 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_types', '0008_auto_20221212_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lnobjconnections',
            options={'ordering': ['ln_inst'], 'verbose_name': ' -Удалить- Связь между экземплярами логических узлов и объектами', 'verbose_name_plural': '-Удалить- Связи между экземплярами логических узлов и объектами'},
        ),
        migrations.CreateModel(
            name='LNtypeObjConnections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ln_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_types.lnobject', verbose_name='Объект лог. узла')),
                ('ln_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_types.logicnodestypes', verbose_name='Тип логического узла')),
            ],
            options={
                'verbose_name': 'Связь между типом логического узла и объектами',
                'verbose_name_plural': 'Связи между типами логических узлов и объектами',
                'ordering': ['ln_type'],
            },
        ),
    ]
