# Generated by Django 3.2.16 on 2022-12-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_types', '0010_auto_20221213_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='SG_modes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Статусы програмного переключателя')),
            ],
            options={
                'verbose_name': 'Программный переключатель',
                'verbose_name_plural': 'Программные переключатели',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='logicnodeinstantiated',
            name='class_name',
            field=models.CharField(max_length=4, verbose_name='Класс (PDIF)'),
        ),
        migrations.AlterField(
            model_name='logicnodeinstantiated',
            name='short_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Краткое имя (БУ, ДЗТ)'),
        ),
        migrations.AddField(
            model_name='lnobject',
            name='sg_modes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base_types.sg_modes', verbose_name='Состояние программного ключа'),
        ),
    ]
