# Generated by Django 3.2.16 on 2022-12-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_types', '0011_auto_20221220_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sg_modes',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Статусы програмного переключателя'),
        ),
    ]
