# Generated by Django 3.2.16 on 2022-12-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_types', '0013_auto_20221221_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputsAndLNs',
        ),
    ]
