# Generated by Django 3.2.16 on 2022-12-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_types', '0014_delete_inputsandlns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnobject',
            name='sgras_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Обозначение РАС/Уставка'),
        ),
    ]
